development:
  clients:
    default:
      database: weblinc_core_development
      hosts:
        - localhost:27017
      options:
  options:
    use_activesupport_time_zone: false
test:
  clients:
    default:
      database: weblinc_core_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary_preferred
        max_pool_size: 1
  options:
    use_activesupport_time_zone: false
